using BackgroundJobExample.EntityFrameworkCore;
using Xunit;

namespace BackgroundJobExample.EntityFrameworkCore;

public class BackgroundJobExampleEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<BackgroundJobExampleEntityFrameworkCoreFixture>
{

}
